@extends('layouts.cms')
@section('title','Playground')
@section('content')
<style>
.playground-head p{margin:5px 0 0}.playground-guide{background:#171717;border:1px solid #333;border-radius:12px;color:#bbb;line-height:1.5;margin-bottom:17px;padding:13px}.playground-guide strong{color:#fff}.playground-tools{display:flex;gap:10px;margin-bottom:18px}.playground-tools input{max-width:560px}.playground-status{align-items:center;color:#aaa;display:flex;font-size:12px;margin-left:auto}.playground-status.success{color:#86efac}.playground-status.error{color:#fca5a5}.playground-grid{display:grid;gap:16px;grid-template-columns:repeat(auto-fill,minmax(180px,1fr))}.play-card{background:#111;border:3px solid #333;border-radius:13px;color:#eee;overflow:hidden;padding:0;text-align:left;transition:border-color .15s,transform .15s}.play-card[hidden]{display:none}.play-card:hover{border-color:#888;transform:translateY(-2px)}.play-card.is-source{border-color:#fff}.play-card.is-complete{border-color:#22c55e}.play-card:disabled{cursor:wait;opacity:.65}.play-card img{aspect-ratio:1;background:#050505;display:block;object-fit:cover;width:100%}.play-card__copy{display:block;padding:11px}.play-card__copy strong,.play-card__copy small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.play-card__copy small{color:#999;font-size:10px;margin-top:4px}.play-card__meta{align-items:center;display:flex!important;justify-content:space-between}.play-card__score{color:var(--primary)}.play-card.is-unavailable{cursor:not-allowed;opacity:.55}.play-card.is-unavailable:hover{border-color:#333;transform:none}@media(max-width:650px){.playground-tools{align-items:stretch;flex-direction:column}.playground-status{margin-left:0}.playground-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
<div class="toolbar playground-head"><div><h1>Playground</h1><p class="hint">Copy artwork from one card to another without swapping.</p></div><span class="badge">{{ $cards->count() }} cards with graphics</span></div>
<div class="playground-guide"><strong>1.</strong> Click the card whose graphic you want to copy. It receives a white border. <strong>2.</strong> Click a different card. The second card receives the first card's graphic. Both borders turn green when the copy succeeds.</div>
<div class="playground-tools"><input id="playgroundSearch" type="search" placeholder="Search by card title or ID" autocomplete="off"><span id="playgroundStatus" class="playground-status" aria-live="polite">Select a source card.</span></div>
<div id="playgroundGrid" class="playground-grid">
@forelse($cards as $card)
<button class="play-card{{ $card['asset_path'] ? '' : ' is-unavailable' }}" type="button" title="{{ $card['title'] }}{{ $card['title_bs'] ? ' / '.$card['title_bs'] : '' }}" data-play-card data-card-id="{{ $card['id'] }}" data-title="{{ Str::lower(trim($card['id'].' '.$card['title'].' '.$card['title_bs'])) }}" data-asset-path="{{ $card['asset_path'] }}" data-assign-url="{{ $card['assign_url'] }}" @disabled(!$card['asset_path'])><img src="{{ $card['image'] }}" alt="Artwork for {{ $card['title'] }}" loading="lazy"><span class="play-card__copy"><strong>#{{ $card['id'] }} · {{ $card['title'] }}</strong>@if($card['title_bs'])<small>{{ $card['title_bs'] }}</small>@endif<span class="play-card__meta"><small>{{ $card['stack'] }}</small><small class="play-card__score">{{ $card['score'] }}</small></span></span></button>
@empty<div class="panel">No cards with graphics were found.</div>@endforelse
</div>
@endsection
@push('scripts')
<script>
(()=>{const csrf=document.querySelector('meta[name="csrf-token"]').content,cards=[...document.querySelectorAll('[data-play-card]')],search=document.getElementById('playgroundSearch'),status=document.getElementById('playgroundStatus');let source=null,busy=false;
const setStatus=(message,type='')=>{status.textContent=message;status.className=`playground-status${type?` ${type}`:''}`};
const clearResult=()=>cards.forEach(card=>card.classList.remove('is-complete'));
search.addEventListener('input',()=>{const query=search.value.trim().toLocaleLowerCase();cards.forEach(card=>card.hidden=query&&!card.dataset.title.toLocaleLowerCase().includes(query))});
cards.forEach(card=>card.addEventListener('click',async()=>{if(busy||card.disabled)return;if(!source){clearResult();source=card;source.classList.add('is-source');setStatus(`Source selected: card #${source.dataset.cardId}. Choose the target card.`);return}if(card===source){source.classList.remove('is-source');source=null;setStatus('Source selection cleared. Select a source card.');return}busy=true;cards.forEach(item=>item.disabled=true);setStatus(`Copying graphic from #${source.dataset.cardId} to #${card.dataset.cardId}…`);try{const response=await fetch(card.dataset.assignUrl,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({asset_path:source.dataset.assetPath})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Graphic could not be copied.');card.querySelector('img').src=data.image;card.dataset.assetPath=source.dataset.assetPath;source.classList.remove('is-source');source.classList.add('is-complete');card.classList.add('is-complete');setStatus(`Graphic copied from card #${source.dataset.cardId} to card #${card.dataset.cardId}.`,'success');source=null}catch(error){setStatus(error.message||'Graphic could not be copied.','error')}finally{busy=false;cards.forEach(item=>item.disabled=item.classList.contains('is-unavailable'))}}));})();
</script>
@endpush
