<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Http\Resources\GameResource; use App\Models\{Card,Game,Move,User}; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str;
class GameController extends Controller {
 private function full(Game $game): GameResource { return new GameResource($game->load(['members','currentCard','moves'=>fn($q)=>$q->with(['player','card'])->latest()])); }
 public function index(){return GameResource::collection(Game::with('members')->latest()->get());}
 public function store(Request $r){$d=$r->validate(['name'=>'required|string|max:255','email'=>'nullable|email']); return DB::transaction(function()use($d){$user=User::create($d); do{$letters='';for($i=0;$i<4;$i++)$letters.=chr(random_int(65,90));$chars=str_split($letters.random_int(1000,9999));shuffle($chars);$code=implode($chars);}while(Game::whereCode($code)->exists()); $game=Game::create(['code'=>$code,'owner_id'=>$user->id]); $game->members()->attach($user); return response()->json(['game'=>$this->full($game),'user'=>new \App\Http\Resources\UserResource($user)],201);});}
 public function show(Game $game){return $this->full($game);} public function byCode(string $code){$game=Game::where('code',strtoupper($code))->firstOrFail(); return $this->full($game);}
 public function update(Request $r,Game $game){$game->update($r->validate(['started'=>'sometimes|boolean']));return $this->full($game);} public function destroy(Game $game){$game->delete();return response()->noContent();}
 public function join(Request $r,string $code){$d=$r->validate(['name'=>'required|string|max:255','email'=>'nullable|email']); return DB::transaction(function()use($d,$code){$game=Game::where('code',strtoupper($code))->lockForUpdate()->firstOrFail(); abort_if($game->started,422,'Game already started.'); abort_if($game->members()->count()>=8,422,'No more available seats in this room.'); $user=User::create($d); $game->members()->attach($user); return response()->json(['game'=>$this->full($game),'user'=>new \App\Http\Resources\UserResource($user)],201);});}
 public function start(Request $r,Game $game){$r->validate(['user_id'=>'required|integer']); abort_unless($game->owner_id===$r->integer('user_id'),403); return DB::transaction(function()use($game){$game->load('members'); if(!$game->started){$needed=$game->members->count()*3+1; $cards=Card::inRandomOrder()->limit($needed)->get(); abort_if($cards->count()<$needed,422,'Not enough cards. Run the card seeder.'); foreach($game->members as $member){foreach($cards->splice(0,3) as $card){DB::table('game_cards')->insert(['game_id'=>$game->id,'user_id'=>$member->id,'card_id'=>$card->id,'created_at'=>now(),'updated_at'=>now()]);}} $current=$cards->shift(); DB::table('game_cards')->insert(['game_id'=>$game->id,'user_id'=>null,'card_id'=>$current->id,'created_at'=>now(),'updated_at'=>now()]); $game->update(['started'=>true,'current_card_id'=>$current->id]);} return $this->full($game);});}
 public function move(Request $r,Game $game){$d=$r->validate(['player_id'=>'required|integer','correct'=>'required|boolean']); abort_unless($game->members()->where('users.id',$d['player_id'])->exists(),422,'Player is not in this game.'); abort_unless($game->started,422,'Game has not started.'); $move=Move::create(['game_id'=>$game->id,'player_id'=>$d['player_id'],'card_id'=>$game->current_card_id,'correct'=>$d['correct']]); if($d['correct'])DB::table('game_cards')->where('game_id',$game->id)->where('card_id',$game->current_card_id)->update(['user_id'=>$d['player_id'],'updated_at'=>now()]); $used=DB::table('game_cards')->where('game_id',$game->id)->pluck('card_id'); $next=Card::whereNotIn('id',$used)->inRandomOrder()->first(); if($next){DB::table('game_cards')->insert(['game_id'=>$game->id,'user_id'=>null,'card_id'=>$next->id,'created_at'=>now(),'updated_at'=>now()]);$game->update(['current_card_id'=>$next->id]);} return response()->json(['move'=>new \App\Http\Resources\MoveResource($move->load(['player','card'])),'game'=>$this->full($game)]);}
}
