@extends('layouts.cms')
@section('title','Stacks')
@section('content')
<div class="toolbar"><div><h1>Stacks</h1><p class="hint">Configure the pack name, native color, localized description and code icon.</p></div></div>
<form class="panel grid" method="post" action="{{ route('cms.stacks.store') }}" style="grid-template-columns:1fr 120px 180px 2fr 2fr auto;align-items:end">@csrf<div><label>Name</label><input name="name" required placeholder="New stack name"></div><div><label>Color</label><input name="color" type="color" value="#facc15"></div><div><label>Code icon</label><select name="icon_key">@foreach($icons as $icon)<option value="{{ $icon }}">{{ $icon }}</option>@endforeach</select></div><div><label>Description EN</label><input name="description" required></div><div><label>Description BS</label><input name="description_bs" required></div><button>Add stack</button></form>
<div class="panel table-wrap" style="margin-top:16px"><table><thead><tr><th>Stack configuration</th><th>Slug</th><th>Cards</th><th></th></tr></thead><tbody>
@foreach($stacks as $stack)<tr><td><form id="stack-{{ $stack->id }}" class="grid" method="post" action="{{ route('cms.stacks.update',$stack) }}" style="grid-template-columns:1fr 90px 150px 2fr 2fr;min-width:760px">@csrf @method('PATCH')<div><label>Name</label><input name="name" value="{{ $stack->name }}" required></div><div><label>Color</label><input name="color" type="color" value="{{ $stack->color }}"></div><div><label>Code icon</label><select name="icon_key">@foreach($icons as $icon)<option value="{{ $icon }}" @selected($stack->icon_key===$icon)>{{ $icon }}</option>@endforeach</select></div><div><label>Description EN</label><input name="description" value="{{ $stack->description }}" required></div><div><label>Description BS</label><input name="description_bs" value="{{ $stack->description_bs }}" required></div></form></td><td>{{ $stack->slug }}</td><td>{{ $stack->cards_count }}</td><td><div class="actions"><button form="stack-{{ $stack->id }}">Save</button>@if(!$stack->cards_count)<form method="post" action="{{ route('cms.stacks.destroy',$stack) }}">@csrf @method('DELETE')<button class="danger">Delete</button></form>@endif</div></td></tr>@endforeach
</tbody></table></div>
@endsection
