@extends('layouts.cms')
@section('title','Gallery')
@section('content')
<style>
body.gallery-modal-open{overflow:hidden}.gallery-head p{margin:5px 0 0}.gallery-tools{display:flex;gap:10px;margin-bottom:18px}.gallery-tools input{max-width:520px}.gallery-grid{display:grid;gap:16px;grid-template-columns:repeat(auto-fill,minmax(180px,1fr))}.gallery-item{background:#111;border:1px solid #333;border-radius:13px;color:#eee;overflow:hidden;padding:0;text-align:left}.gallery-item:hover{border-color:var(--primary);transform:translateY(-2px)}.gallery-item img{aspect-ratio:1;background:#050505;display:block;object-fit:cover;width:100%}.gallery-item__copy{display:block;padding:11px}.gallery-item__copy strong,.gallery-item__copy small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.gallery-item__copy small{color:#888;font-size:10px;margin-top:4px}.gallery-item__count{color:var(--primary)!important}.gallery-empty{color:#888;grid-column:1/-1;padding:40px;text-align:center}.assign-modal{background:rgba(0,0,0,.92);display:flex;inset:0;padding:24px;position:fixed;z-index:2200}.assign-modal[hidden]{display:none}.assign-modal__panel{background:#171717;border:1px solid #444;border-radius:16px;display:flex;flex-direction:column;margin:auto;max-height:92vh;max-width:1080px;padding:22px;width:100%}.assign-modal__head{align-items:flex-start;display:flex;gap:18px;justify-content:space-between}.assign-modal__selection{align-items:center;display:flex;gap:13px;min-width:0}.assign-modal__selection img{background:#050505;border-radius:9px;height:76px;object-fit:cover;width:76px}.assign-modal__selection h2{margin:0}.assign-modal__selection p{margin:5px 0 0;max-width:600px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.card-search{margin-top:16px}.card-list{display:grid;gap:10px;grid-template-columns:repeat(auto-fill,minmax(245px,1fr));margin-top:14px;overflow:auto;padding:2px}.card-choice{align-items:center;background:#0c0c0d;border:1px solid #383838;color:#eee;display:grid;gap:11px;grid-template-columns:54px 1fr auto;padding:9px;text-align:left}.card-choice:hover{border-color:var(--primary)}.card-choice:disabled{cursor:wait;opacity:.55}.card-choice img,.card-choice__empty{align-items:center;background:#050505;border-radius:7px;display:flex;height:54px;justify-content:center;object-fit:cover;width:54px}.card-choice__copy{min-width:0}.card-choice strong,.card-choice small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.card-choice small{color:#999;font-size:10px;margin-top:4px}.card-choice b{color:var(--primary);font-size:12px}.assign-status{color:#aaa;font-size:12px;margin:12px 0 0;min-height:18px}.assign-status.success{color:#86efac}.assign-status.error{color:#fca5a5}@media(max-width:650px){.gallery-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.assign-modal{padding:9px}.assign-modal__panel{padding:13px}.assign-modal__selection img{height:54px;width:54px}.card-list{grid-template-columns:1fr}}
</style>
<div class="toolbar gallery-head"><div><h1>Gallery</h1><p class="hint">All stored card graphics. Select a graphic, then choose the card that should use it.</p></div><span class="badge">{{ $assets->count() }} graphics</span></div>
<div class="gallery-tools"><input id="gallerySearch" type="search" placeholder="Search filename or folder"><select id="galleryFormat" style="max-width:170px"><option value="all">All formats</option><option value="jpg">JPG</option><option value="webp">WebP</option><option value="other">Other</option></select></div>
<div id="galleryGrid" class="gallery-grid">
@forelse($assets as $asset)
<button class="gallery-item" type="button" data-gallery-item data-path="{{ $asset['path'] }}" data-url="{{ $asset['url'] }}" data-filename="{{ $asset['filename'] }}" data-folder="{{ $asset['folder'] }}" data-format="{{ $asset['format'] }}"><img src="{{ $asset['url'] }}" alt="{{ $asset['filename'] }}" loading="lazy"><span class="gallery-item__copy"><strong>{{ $asset['filename'] }}</strong><small>{{ $asset['folder'] }}</small><small class="gallery-item__count">Used by {{ $asset['cards'] }} card{{ $asset['cards'] === 1 ? '' : 's' }}</small></span></button>
@empty<div class="gallery-empty">No graphics found under public storage/cards or public storage/generated.</div>@endforelse
</div>
<div id="assignModal" class="assign-modal" role="dialog" aria-modal="true" aria-labelledby="assignTitle" hidden><section class="assign-modal__panel"><div class="assign-modal__head"><div class="assign-modal__selection"><img id="assignArtwork" alt="Selected graphic"><div><h2 id="assignTitle">Assign graphic to a card</h2><p id="assignPath" class="hint"></p></div></div><button id="assignClose" class="secondary" type="button">Close</button></div><label for="cardSearch" style="margin-top:16px">Search card titles</label><input id="cardSearch" class="card-search" type="search" placeholder="Type an English or Bosnian card title…" autocomplete="off"><p id="assignStatus" class="assign-status" aria-live="polite"></p><div id="cardList" class="card-list">@foreach($cards as $card)<button class="card-choice" type="button" data-card-choice data-title="{{ Str::lower(trim($card['title'].' '.$card['title_bs'])) }}" data-assign-url="{{ $card['assign_url'] }}" data-card-id="{{ $card['id'] }}">@if($card['image'])<img src="{{ $card['image'] }}" alt="" loading="lazy">@else<div class="card-choice__empty">⚡</div>@endif<div class="card-choice__copy"><strong>{{ $card['title'] }}</strong>@if($card['title_bs'])<small>{{ $card['title_bs'] }}</small>@endif<small>#{{ $card['id'] }} · {{ $card['stack'] }}</small></div><b>{{ $card['score'] }}</b></button>@endforeach</div></section></div>
@endsection
@push('scripts')
<script>
(()=>{const csrf=document.querySelector('meta[name="csrf-token"]').content,items=[...document.querySelectorAll('[data-gallery-item]')],gallerySearch=document.getElementById('gallerySearch'),format=document.getElementById('galleryFormat'),modal=document.getElementById('assignModal'),artwork=document.getElementById('assignArtwork'),pathLabel=document.getElementById('assignPath'),closeButton=document.getElementById('assignClose'),cardSearch=document.getElementById('cardSearch'),cards=[...document.querySelectorAll('[data-card-choice]')],status=document.getElementById('assignStatus');let selected=null,restoreFocus=null,busy=false;
const filterGallery=()=>{const query=gallerySearch.value.trim().toLowerCase(),selectedFormat=format.value;items.forEach(item=>{item.hidden=(selectedFormat!=='all'&&item.dataset.format!==selectedFormat)||(query&&!`${item.dataset.filename} ${item.dataset.folder}`.toLowerCase().includes(query))})};gallerySearch.addEventListener('input',filterGallery);format.addEventListener('change',filterGallery);
const filterCards=()=>{const query=cardSearch.value.trim().toLocaleLowerCase();cards.forEach(card=>card.hidden=query&&!card.dataset.title.toLocaleLowerCase().includes(query))};cardSearch.addEventListener('input',filterCards);
const close=()=>{if(busy)return;modal.hidden=true;document.body.classList.remove('gallery-modal-open');selected=null;cardSearch.value='';filterCards();status.textContent='';status.className='assign-status';restoreFocus?.focus()};
items.forEach(item=>item.addEventListener('click',()=>{selected=item.dataset.path;restoreFocus=item;artwork.src=item.dataset.url;pathLabel.textContent=item.dataset.path;modal.hidden=false;document.body.classList.add('gallery-modal-open');cardSearch.focus()}));closeButton.addEventListener('click',close);modal.addEventListener('click',event=>{if(event.target===modal)close()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)close()});
cards.forEach(card=>card.addEventListener('click',async()=>{if(!selected||busy)return;busy=true;card.disabled=true;status.textContent='Assigning graphic…';status.className='assign-status';try{const response=await fetch(card.dataset.assignUrl,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({asset_path:selected})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Graphic could not be assigned.');const image=card.querySelector('img');if(image)image.src=data.image;else{const empty=card.querySelector('.card-choice__empty'),replacement=document.createElement('img');replacement.src=data.image;replacement.alt='';empty.replaceWith(replacement)}status.textContent='Graphic assigned successfully.';status.className='assign-status success'}catch(error){status.textContent=error.message||'Graphic could not be assigned.';status.className='assign-status error'}finally{busy=false;card.disabled=false}}));})();
</script>
@endpush
