@extends('layouts.cms')
@section('title','Cards')
@section('content')
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Outfit:wght@400;700&display=swap" rel="stylesheet">
<style>.inline-score{font-variant-numeric:tabular-nums}.inline-score__value{border-bottom:1px dashed #777;cursor:pointer;display:inline-block;min-width:48px;user-select:none}.inline-score__input{padding:7px;width:88px}.inline-score.is-saving{opacity:.55}.inline-score.is-error .inline-score__input{border-color:#ef4444}.inline-score__error{color:#f87171;display:block;font-size:11px;margin-top:4px;max-width:150px}.art-thumb{display:inline-block;position:relative}.art-thumb .thumb{display:block}.art-thumb__zoom{background:#111;border:1px solid #555;bottom:-4px;color:#fff;font-size:11px;padding:4px 6px;position:absolute;right:-7px}.enhanced-flag{background:#713f12;color:#fde68a;display:block;margin-top:8px;text-align:center}.enhanced-flag[hidden]{display:none}.artwork-action{flex:0 0 112px;width:112px}.actions button:disabled,.bulk-actions button:disabled{cursor:not-allowed;opacity:.4}.card-selector,.select-visible-cards{height:18px;width:18px}.bulk-actions{align-items:center;background:#101922;border:1px solid #24445c;border-radius:12px;display:flex;gap:10px;margin:0 0 16px;padding:12px 14px}.bulk-actions button{white-space:nowrap}.bulk-actions__status{color:#a3a3a3;font-size:12px;margin-left:auto}.translation-copy{border-left:2px solid #3f3f46;margin-top:8px;padding-left:9px}.translation-copy b{color:#facc15}.row-task-status{display:block;font-size:11px;margin-top:6px;min-height:16px}.row-task-status.is-error{color:#f87171}.row-task-status.is-success{color:#86efac}body.table-cropper-open{overflow:hidden}.table-cropper{background:rgba(0,0,0,.96);display:grid;grid-template-columns:minmax(0,1fr) 290px;inset:0;padding:24px;position:fixed;z-index:2100}.table-cropper[hidden]{display:none}.table-cropper__stage{align-items:center;display:flex;justify-content:center;min-height:0}.table-cropper__frame{aspect-ratio:1;background:#000;border:2px solid var(--primary);cursor:grab;max-height:calc(100vh - 48px);max-width:calc(100vh - 48px);width:min(100%,calc(100vh - 48px))}.table-cropper__frame.dragging{cursor:grabbing}.table-cropper canvas{display:block;height:100%;touch-action:none;width:100%}.table-cropper__panel{align-self:center;background:#171717;border:1px solid #333;border-radius:16px;padding:22px}.table-cropper__panel h2{color:var(--primary);margin-top:0}.table-cropper__zoom{align-items:center;display:flex;gap:10px;margin:10px 0 22px}.table-cropper__zoom output{min-width:46px;text-align:right}.table-cropper__actions{display:grid;gap:10px}.table-cropper__actions button{width:100%}@media(max-width:760px){.bulk-actions{align-items:stretch;flex-direction:column}.bulk-actions__status{margin-left:0}.table-cropper{grid-template-columns:1fr;grid-template-rows:minmax(0,1fr) auto;padding:14px}.table-cropper__frame{max-height:calc(100vh - 240px);max-width:calc(100vh - 240px)}.table-cropper__panel{padding:14px}.table-cropper__actions{grid-template-columns:1fr 1fr 1fr}}</style>
<style>.art-thumb__controls{bottom:-7px;display:flex;gap:4px;position:absolute;right:-10px}.art-thumb__controls .art-thumb__zoom,.art-thumb__controls .art-thumb__change{background:#111;border:1px solid #555;color:#fff;font-size:10px;padding:4px 6px;position:static}.art-thumb__preview{background:#090909;border:2px solid #facc15;border-radius:10px;box-shadow:0 18px 45px rgba(0,0,0,.65);display:none;height:280px;left:calc(100% + 14px);object-fit:cover;position:absolute;top:50%;transform:translateY(-50%);width:280px;z-index:1200}.art-thumb:hover .art-thumb__preview,.art-thumb:focus-within .art-thumb__preview{display:block}.artwork-picker{background:rgba(0,0,0,.92);display:flex;inset:0;padding:24px;position:fixed;z-index:2200}.artwork-picker[hidden]{display:none}.artwork-picker__panel{background:#171717;border:1px solid #444;border-radius:16px;display:flex;flex-direction:column;margin:auto;max-height:90vh;max-width:1040px;padding:22px;width:100%}.artwork-picker__head{align-items:center;display:flex;gap:16px;justify-content:space-between}.artwork-picker__grid{display:grid;gap:12px;grid-template-columns:repeat(auto-fill,minmax(130px,1fr));margin-top:16px;overflow:auto;padding:2px}.artwork-choice{background:#0a0a0a;border:1px solid #444;border-radius:10px;color:#eee;padding:8px;text-align:left}.artwork-choice:hover{border-color:#facc15}.artwork-choice img{aspect-ratio:1;display:block;object-fit:cover;width:100%}.artwork-choice span{display:block;font-size:11px;margin-top:7px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:760px){.art-thumb__preview{display:none!important}.artwork-picker{padding:10px}.artwork-picker__panel{padding:14px}}</style>
<style>.status-trigger{border:0;cursor:pointer;font:inherit}.status-modal{background:rgba(0,0,0,.78);display:flex;inset:0;padding:20px;position:fixed;z-index:2300}.status-modal[hidden]{display:none}.status-modal__panel{background:#171717;border:1px solid #444;border-radius:14px;margin:auto;padding:20px;width:min(100%,340px)}.status-modal__panel h2{margin:0 0 6px}.status-modal__options{display:grid;gap:10px;margin-top:18px}.status-modal__options button{width:100%}.artwork-format-download{color:#fff;text-decoration:none}.artwork-format-download:hover{outline:1px solid #facc15}.art-thumb__controls .art-thumb__zoom,.art-thumb__controls .art-thumb__change{align-items:center;display:inline-flex;height:30px;justify-content:center;padding:0;width:30px}.art-thumb__controls svg{display:block;height:16px;pointer-events:none;width:16px}</style>
<div class="toolbar"><div><h1>Cards</h1><p class="hint">Double-click a score to edit it. Press Enter or click outside to save.</p></div><a class="btn" href="{{ route('cms.cards.create') }}">+ New card</a></div>
<form class="toolbar" method="get"><input name="q" value="{{ request('q') }}" placeholder="Search title or description"><select name="stack" style="max-width:180px"><option value="">All packs</option>@foreach($stacks as $stack)<option value="{{ $stack->id }}" @selected((string)request('stack')===(string)$stack->id)>{{ $stack->name }}</option>@endforeach</select><select name="status" style="max-width:180px"><option value="">All statuses</option><option value="0" @selected(request('status')==='0')>Drafts</option><option value="1" @selected(request('status')==='1')>Approved</option></select><select name="enhanced" style="max-width:190px"><option value="">All enhancement</option><option value="0" @selected(request('enhanced')==='0')>Unenhanced</option><option value="1" @selected(request('enhanced')==='1')>Enhanced</option></select><select name="format" style="max-width:150px"><option value="">All formats</option><option value="webp" @selected(request('format')==='webp')>WebP</option><option value="jpg" @selected(request('format')==='jpg')>JPG</option></select><button>Filter</button></form>
<div class="bulk-actions" aria-label="Bulk card actions"><strong><span id="selectedCardCount">0</span> selected</strong><button id="bulkEnhance" class="secondary" type="button" disabled>Enhance selected</button><button id="bulkWebp" class="secondary" type="button" disabled>Convert selected to WebP</button><button id="bulkTranslate" class="secondary" type="button" disabled>Bosnian translate selected</button><button id="swapArtwork" class="secondary" type="button" disabled>Swap artwork</button><button id="bulkDelete" class="danger" type="button" disabled>Delete selected</button><span id="bulkActionStatus" class="bulk-actions__status" aria-live="polite">Select cards from this page.</span></div>
@php($weightDirection = request('sort') === 'artwork_weight' && request('direction') === 'desc' ? 'asc' : 'desc')
@php($weightSortUrl = route('cms.cards.index', array_merge(request()->except(['sort','direction','page']), ['sort' => 'artwork_weight', 'direction' => $weightDirection])))
@php($formatDirection = request('sort') === 'artwork_format' && request('direction') === 'desc' ? 'asc' : 'desc')
@php($formatSortUrl = route('cms.cards.index', array_merge(request()->except(['sort','direction','page']), ['sort' => 'artwork_format', 'direction' => $formatDirection])))
@php($idDirection = request('sort') === 'card_id' && request('direction') === 'desc' ? 'asc' : 'desc')
@php($idSortUrl = route('cms.cards.index', array_merge(request()->except(['sort','direction','page']), ['sort' => 'card_id', 'direction' => $idDirection])))
<div class="panel table-wrap"><table><thead><tr><th><input id="selectVisibleCards" class="select-visible-cards" type="checkbox" aria-label="Select all cards on this page"></th><th><a href="{{ $idSortUrl }}">ID @if(request('sort') === 'card_id'){{ request('direction') === 'desc' ? '↓' : '↑' }}@endif</a></th><th>Art</th><th><a href="{{ $weightSortUrl }}">Size @if(request('sort') === 'artwork_weight'){{ request('direction') === 'desc' ? '↓' : '↑' }}@endif</a></th><th><a href="{{ $formatSortUrl }}">Format @if(request('sort') === 'artwork_format'){{ request('direction') === 'desc' ? '↓' : '↑' }}@endif</a></th><th>Card</th><th>Score</th><th>Status</th><th>Stack</th><th></th></tr></thead><tbody>
@forelse($cards as $card)
@php($image = $card->image && $card->image !== '0' ? (str_starts_with($card->image,'http') ? $card->image : url('/card-images/'.preg_replace('#^storage/#','',$card->image))) : null)
@php($canEnhance = $image && !str_starts_with($card->image,'http://') && !str_starts_with($card->image,'https://'))
@php($translated = filled($card->title_bs) && (!filled($card->subtitle) || filled($card->subtitle_bs)))
<tr data-card-row data-card-id="{{ $card->id }}" data-title="{{ $card->title }}" data-subtitle="{{ $card->subtitle }}" data-translate-url="{{ route('cms.cards.translate-bs',$card) }}" data-assign-url="{{ route('cms.cards.assign-artwork',$card) }}"><td><input class="card-selector" type="checkbox" aria-label="Select {{ $card->title }}"></td><td>{{ $card->id }}</td><td><div class="art-thumb"><a href="{{ route('cms.cards.edit',['card'=>$card,'return'=>request()->fullUrl()]) }}" title="Edit {{ $card->title }}">@if($image)<img id="card-art-{{ $card->id }}" class="thumb" src="{{ $image }}" alt="Artwork for {{ $card->title }}">@else<div class="thumb placeholder">⚡</div>@endif</a>@if($image)<img class="art-thumb__preview" src="{{ $image }}" alt=""><div class="art-thumb__controls"><button class="art-thumb__zoom" type="button" data-crop-artwork data-crop-source="{{ $image }}" data-crop-url="{{ route('cms.cards.crop-generated',$card) }}" aria-label="Crop artwork for {{ $card->title }}" title="Crop artwork">Zoom</button><button class="art-thumb__change" type="button" data-change-artwork>Change</button></div>@else<div class="art-thumb__controls"><button class="art-thumb__change" type="button" data-change-artwork>Change</button></div>@endif</div><span class="badge enhanced-flag" @if(!$card->artwork_enhanced) hidden @endif>ENHANCED</span></td>
<td>@if($card->artwork_bytes !== null){{ $card->artwork_bytes < 1024 ? $card->artwork_bytes.' B' : number_format($card->artwork_bytes / 1024, 0).' KB' }}@else<span class="hint">—</span>@endif</td><td><span class="badge">{{ $card->artwork_extension }}</span></td><td><b>{{ $card->title }}</b><div class="hint">{{ Str::limit($card->subtitle,70) }}</div><span class="badge translation-status" style="background:{{ $translated ? '#14532d' : '#3f3f46' }}">{{ $translated ? 'TRANSLATED' : 'NOT TRANSLATED' }}</span><b class="card-title-bs" hidden>{{ $card->title_bs }}</b><span class="card-subtitle-bs" hidden>{{ $card->subtitle_bs }}</span><span class="row-task-status" aria-live="polite"></span></td><td><div class="inline-score" data-url="{{ route('cms.cards.score',$card) }}" data-score="{{ number_format($card->score,2,'.','') }}"><span class="inline-score__value" title="Double-click to edit" tabindex="0">{{ number_format($card->score,2) }}</span><input class="inline-score__input" type="number" min="0" max="100" step="0.01" inputmode="decimal" aria-label="Score for {{ $card->title }}" hidden><span class="inline-score__error" role="alert" hidden></span></div></td><td><button class="badge status-trigger" type="button" style="background:{{ $card->status?'#14532d':'#3f3f46' }}" data-status-trigger data-status-url="{{ route('cms.cards.status',$card) }}" data-card-title="{{ $card->title }}" aria-label="Change status for {{ $card->title }}">{{ $card->status?'APPROVED':'DRAFT' }}</button></td><td><span class="badge">{{ $card->stack?->name ?? $card->deck }}</span></td>
<td><div class="actions"><button class="secondary artwork-action" type="button" data-mode="{{ $canEnhance?'enhance':'generate' }}" data-url="{{ $canEnhance?route('cms.cards.enhance-artwork',$card):route('cms.cards.generate',$card) }}" data-enhance-url="{{ route('cms.cards.enhance-artwork',$card) }}" data-crop-url="{{ route('cms.cards.crop-generated',$card) }}">{{ $canEnhance?'Enhance':'Generate' }}</button>@if($canEnhance)<button class="secondary webp-action" type="button" data-url="{{ route('cms.cards.convert-webp',$card) }}">WebP</button>@endif<button class="secondary export-card" type="button" data-title="{{ $card->title }}" data-subtitle="{{ $card->subtitle }}" data-score="{{ number_format($card->score,2,'.','') }}" data-image="{{ $image ?: route('cms.native-card-artwork') }}" data-fallback="{{ $image ? '0' : '1' }}">Export</button><form method="post" action="{{ route('cms.cards.destroy',$card) }}" onsubmit="return confirm('Delete this card?')">@csrf @method('DELETE')<button class="danger">Delete</button></form></div></td></tr>
@empty<tr><td colspan="10">No cards found.</td></tr>@endforelse
</tbody></table></div>{{ $cards->links('cms.pagination') }}
<div id="tableCropper" class="table-cropper" role="dialog" aria-modal="true" aria-labelledby="tableCropperTitle" hidden><div class="table-cropper__stage"><div id="tableCropFrame" class="table-cropper__frame"><canvas id="tableCropCanvas" width="768" height="768"></canvas></div></div><aside class="table-cropper__panel"><h2 id="tableCropperTitle">Crop artwork</h2><p class="hint">Drag to reposition and zoom to choose the 768 × 768 WebP crop.</p><label for="tableCropZoom">Zoom</label><div class="table-cropper__zoom"><input id="tableCropZoom" type="range" min="1" max="3" step="0.01" value="1"><output id="tableCropZoomValue">100%</output></div><div class="table-cropper__actions"><button id="tableCropSave" type="button">Save WebP crop</button><button id="tableCropReset" class="secondary" type="button">Reset</button><button id="tableCropClose" class="secondary" type="button">Close</button></div></aside></div>
<div id="artworkPicker" class="artwork-picker" role="dialog" aria-modal="true" aria-labelledby="artworkPickerTitle" hidden><section class="artwork-picker__panel"><div class="artwork-picker__head"><div><h2 id="artworkPickerTitle">Change artwork</h2><p class="hint">Choose any uploaded card artwork.</p></div><button id="artworkPickerClose" class="secondary" type="button">Close</button></div><div class="artwork-picker__grid">@foreach($artworks as $artwork) @php($artworkUrl = str_starts_with($artwork->image,'http') ? $artwork->image : url('/card-images/'.preg_replace('#^storage/#','',$artwork->image)))<button class="artwork-choice" type="button" data-artwork-source-card="{{ $artwork->id }}"><img src="{{ $artworkUrl }}" alt="Artwork from {{ $artwork->title }}" loading="lazy"><span>{{ $artwork->title }}</span></button>@endforeach</div></section></div>
<div id="statusModal" class="status-modal" role="dialog" aria-modal="true" aria-labelledby="statusModalTitle" hidden><section class="status-modal__panel"><h2 id="statusModalTitle">Change status</h2><p id="statusModalCard" class="hint"></p><form id="statusModalForm" method="post">@csrf<div class="status-modal__options"><button type="submit" name="status" value="1">Approved</button><button class="secondary" type="submit" name="status" value="0">Draft</button><button id="statusModalClose" class="secondary" type="button">Cancel</button></div></form></section></div>
@endsection
@push('scripts')
<script>
const CARD_EXPORT_WIDTH=1200,CARD_EXPORT_HEIGHT=1800,CARD_EXPORT_SCALE=CARD_EXPORT_WIDTH/360;
function roundedRect(ctx,x,y,width,height,radius){const r=Math.min(radius,width/2,height/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+width,y,x+width,y+height,r);ctx.arcTo(x+width,y+height,x,y+height,r);ctx.arcTo(x,y+height,x,y,r);ctx.arcTo(x,y,x+width,y,r);ctx.closePath()}
function fitLines(ctx,text,maxWidth,maxLines){const words=String(text||'').trim().split(/\s+/).filter(Boolean),lines=[];let line='';for(const word of words){const candidate=line?line+' '+word:word;if(ctx.measureText(candidate).width<=maxWidth||!line){line=candidate;continue}lines.push(line);line=word;if(lines.length===maxLines-1)break}if(line&&lines.length<maxLines)lines.push(line);const consumed=lines.join(' ').split(/\s+/).length;if(consumed<words.length&&lines.length){let last=lines.length-1;while(lines[last]&&ctx.measureText(lines[last]+'…').width>maxWidth)lines[last]=lines[last].slice(0,-1);lines[last]+='…'}return lines}
function drawCenteredLines(ctx,text,y,maxWidth,maxLines,lineHeight){const lines=fitLines(ctx,text,maxWidth,maxLines);lines.forEach((line,index)=>ctx.fillText(line,CARD_EXPORT_WIDTH/2,y+(index*lineHeight)));return lines.length}
function loadExportImage(source){return new Promise((resolve,reject)=>{const image=new Image();if(new URL(source,location.href).origin!==location.origin)image.crossOrigin='anonymous';image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Artwork could not be loaded for PNG export.'));image.src=source})}
function drawCover(ctx,image,x,y,width,height){const scale=Math.max(width/image.naturalWidth,height/image.naturalHeight),sourceWidth=width/scale,sourceHeight=height/scale,sourceX=(image.naturalWidth-sourceWidth)/2,sourceY=(image.naturalHeight-sourceHeight)/2;ctx.drawImage(image,sourceX,sourceY,sourceWidth,sourceHeight,x,y,width,height)}
function drawContain(ctx,image,x,y,width,height,scale=.78,translateY=33){const boxWidth=width*scale,boxHeight=height*scale,imageScale=Math.min(boxWidth/image.naturalWidth,boxHeight/image.naturalHeight),drawWidth=image.naturalWidth*imageScale,drawHeight=image.naturalHeight*imageScale;ctx.drawImage(image,x+(width-drawWidth)/2,y+(height-drawHeight)/2+translateY,drawWidth,drawHeight)}
async function exportNativeCard(button){const original=button.textContent;button.disabled=true;button.textContent='Exporting…';try{await Promise.all([document.fonts.load('100px "Bebas Neue"'),document.fonts.load('37px Outfit')]);const image=await loadExportImage(button.dataset.image);const canvas=document.createElement('canvas');canvas.width=CARD_EXPORT_WIDTH;canvas.height=CARD_EXPORT_HEIGHT;const ctx=canvas.getContext('2d');ctx.save();roundedRect(ctx,0,0,CARD_EXPORT_WIDTH,CARD_EXPORT_HEIGHT,60);ctx.clip();ctx.fillStyle='#000';ctx.fillRect(0,0,CARD_EXPORT_WIDTH,CARD_EXPORT_HEIGHT);
const contentX=60,contentWidth=CARD_EXPORT_WIDTH-120,textGap=33,textPaddingY=textGap,textContainerTop=74,titleTop=textContainerTop+textPaddingY;ctx.textAlign='center';ctx.textBaseline='top';ctx.fillStyle='#f8f8f5';ctx.font='100px "Bebas Neue"';const titleLines=fitLines(ctx,button.dataset.title,contentWidth-80,3);titleLines.forEach((line,index)=>ctx.fillText(line,CARD_EXPORT_WIDTH/2,titleTop+index*103));const titleBottom=titleTop+titleLines.length*103;ctx.fillStyle='#8f8f8f';ctx.font='37px Outfit';const subtitleLines=fitLines(ctx,button.dataset.subtitle,contentWidth*.88,3),subtitleLineHeight=50,subtitleStart=titleBottom+(subtitleLines.length?textGap:0);subtitleLines.forEach((line,index)=>ctx.fillText(line,CARD_EXPORT_WIDTH/2,subtitleStart+index*subtitleLineHeight));const textContainerBottom=(subtitleLines.length?subtitleStart+subtitleLines.length*subtitleLineHeight:titleBottom)+textPaddingY;
const artworkX=60,artworkY=textContainerBottom,artworkSize=1080;ctx.save();ctx.beginPath();ctx.rect(artworkX,artworkY,artworkSize,artworkSize);ctx.clip();ctx.fillStyle='#000';ctx.fillRect(artworkX,artworkY,artworkSize,artworkSize);button.dataset.fallback==='1'?drawContain(ctx,image,artworkX,artworkY,artworkSize,artworkSize):drawCover(ctx,image,artworkX,artworkY,artworkSize,artworkSize);ctx.restore();
const overlay=ctx.createLinearGradient(144,0,984,CARD_EXPORT_HEIGHT);overlay.addColorStop(0,'rgba(36,36,36,.62)');overlay.addColorStop(.13,'rgba(17,17,17,.34)');overlay.addColorStop(.3,'rgba(0,0,0,.08)');overlay.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=overlay;ctx.fillRect(0,0,CARD_EXPORT_WIDTH,CARD_EXPORT_HEIGHT);
const footerHeight=347,footerTop=CARD_EXPORT_HEIGHT-footerHeight,tabWidth=373,tabX=(CARD_EXPORT_WIDTH-tabWidth)/2,tabTop=footerTop+115,labelY=(footerTop+tabTop)/2;ctx.fillStyle='#000';ctx.fillRect(0,footerTop,CARD_EXPORT_WIDTH,footerHeight);ctx.strokeStyle='rgba(250,204,21,.35)';ctx.lineWidth=7;roundedRect(ctx,30,30,CARD_EXPORT_WIDTH-60,CARD_EXPORT_HEIGHT-60,37);ctx.stroke();ctx.fillStyle='#facc15';ctx.fillRect(tabX,tabTop,tabWidth,CARD_EXPORT_HEIGHT-tabTop+2);ctx.fillStyle='#facc15';ctx.font='50px "Bebas Neue"';ctx.textBaseline='middle';ctx.fillText('MISERY RATE',CARD_EXPORT_WIDTH/2,labelY);ctx.fillStyle='#09090b';ctx.font='140px "Bebas Neue"';ctx.fillText(Number(button.dataset.score).toFixed(2),CARD_EXPORT_WIDTH/2,footerTop+232);ctx.restore();ctx.strokeStyle='#facc15';ctx.lineWidth=17;roundedRect(ctx,9,9,CARD_EXPORT_WIDTH-18,CARD_EXPORT_HEIGHT-18,51);ctx.stroke();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('PNG creation failed.');const link=document.createElement('a'),slug=(button.dataset.title||'misery-card').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');link.href=URL.createObjectURL(blob);link.download=(slug||'misery-card')+'-hq.png';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}catch(error){alert(error.message||'Card export failed.')}finally{button.disabled=false;button.textContent=original}}
document.querySelectorAll('.export-card').forEach(button=>button.addEventListener('click',()=>exportNativeCard(button)));
const csrfToken=document.querySelector('meta[name="csrf-token"]').content;
const bulkDeleteUrl=@json(route('cms.cards.bulk-destroy')),swapArtworkUrl=@json(route('cms.cards.swap-artwork'));
const thumbnailIcons={zoom:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" aria-hidden="true"><circle cx="11" cy="11" r="6"></circle><path d="m16 16 4 4"></path></svg>',change:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 7h11"></path><path d="m12 4 3 3-3 3"></path><path d="M20 17H9"></path><path d="m12 14-3 3 3 3"></path></svg>'};
function setThumbnailActionIcon(button,type){button.innerHTML=thumbnailIcons[type];button.title=type==='zoom'?'Zoom and crop artwork':'Change artwork';button.setAttribute('aria-label',button.title)}
document.querySelectorAll('[data-crop-artwork]').forEach(button=>setThumbnailActionIcon(button,'zoom'));document.querySelectorAll('[data-change-artwork]').forEach(button=>setThumbnailActionIcon(button,'change'));
(()=>{const modal=document.getElementById('statusModal'),form=document.getElementById('statusModalForm'),card=document.getElementById('statusModalCard'),closeButton=document.getElementById('statusModalClose');let trigger=null;const close=()=>{modal.hidden=true;document.body.classList.remove('table-cropper-open');trigger?.focus();trigger=null};document.querySelectorAll('[data-status-trigger]').forEach(button=>button.addEventListener('click',()=>{trigger=button;form.action=button.dataset.statusUrl;card.textContent=button.dataset.cardTitle;modal.hidden=false;document.body.classList.add('table-cropper-open');closeButton.focus()}));closeButton.addEventListener('click',close);modal.addEventListener('click',event=>{if(event.target===modal)close()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)close()})})();
function refreshArtworkMetadata(row,bytes,extension,imageUrl=null){if(bytes!==undefined&&bytes!==null)row.children[3].textContent=bytes<1024?`${bytes} B`:`${Math.round(bytes/1024)} KB`;if(!extension)return;const source=imageUrl||row.querySelector('.export-card')?.dataset.image,cell=row.children[4];if(!source){cell.innerHTML='<span class="badge"></span>';cell.firstElementChild.textContent=extension;return}let link=cell.querySelector('.artwork-format-download');if(!link){link=document.createElement('a');link.className='badge artwork-format-download';link.title='Right-click to download artwork';cell.replaceChildren(link)}link.textContent=extension;link.href=source;link.download=decodeURIComponent(new URL(source,location.href).pathname.split('/').pop()||`card-artwork.${extension.toLowerCase()}`)}
document.querySelectorAll('[data-card-row]').forEach(row=>{const extension=row.children[4]?.textContent.trim(),source=row.querySelector('.export-card')?.dataset.image;if(extension&&source)refreshArtworkMetadata(row,null,extension,source)});
function refreshRowArtwork(row,imageUrl,enhanced=false){const refreshed=`${imageUrl}${imageUrl.includes('?')?'&':'?'}v=${Date.now()}`,artThumb=row.querySelector('.art-thumb'),exportButton=row.querySelector('.export-card'),flag=row.querySelector('.enhanced-flag');let thumb=row.querySelector('.thumb'),zoom=row.querySelector('[data-crop-artwork]'),preview=row.querySelector('.art-thumb__preview'),controls=row.querySelector('.art-thumb__controls');if(!thumb.matches('img')){const image=document.createElement('img');image.className='thumb';image.alt='Card artwork';thumb.replaceWith(image);thumb=image}thumb.src=refreshed;if(!preview){preview=document.createElement('img');preview.className='art-thumb__preview';preview.alt='';artThumb.appendChild(preview)}preview.src=refreshed;if(!controls){controls=document.createElement('div');controls.className='art-thumb__controls';artThumb.appendChild(controls)}if(!zoom){zoom=document.createElement('button');zoom.className='art-thumb__zoom';zoom.type='button';zoom.setAttribute('data-crop-artwork','');controls.prepend(zoom)}setThumbnailActionIcon(zoom,'zoom');zoom.dataset.cropSource=refreshed;zoom.dataset.cropUrl=row.querySelector('.artwork-action').dataset.cropUrl;if(exportButton){exportButton.dataset.image=refreshed;exportButton.dataset.fallback='0'}if(flag)flag.hidden=!enhanced;return refreshed}
async function runArtworkAction(button,{showAlert=true}={}){
    const row=button.closest('tr'),exportButton=row.querySelector('.export-card'),enhancedFlag=row.querySelector('.enhanced-flag'),mode=button.dataset.mode;
    button.disabled=true;button.textContent=mode==='generate'?'Generating…':'Enhancing…';
    try{
        const response=await fetch(button.dataset.url,{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':csrfToken}}),data=await response.json().catch(()=>({}));
        if(!response.ok)throw new Error(data.message||'Artwork enhancement failed.');
        const refreshedImage=`${data.image}${data.image.includes('?')?'&':'?'}v=${Date.now()}`;refreshArtworkMetadata(row,data.bytes,data.extension,data.image);
        let thumb=row.querySelector('.thumb'),zoom=row.querySelector('[data-crop-artwork]');
        if(!thumb.matches('img')){const image=document.createElement('img');image.className='thumb';image.alt='Card artwork';thumb.replaceWith(image);thumb=image}
        thumb.src=refreshedImage;
        if(!zoom){zoom=document.createElement('button');zoom.className='art-thumb__zoom';zoom.type='button';zoom.setAttribute('data-crop-artwork','');row.querySelector('.art-thumb').appendChild(zoom)}setThumbnailActionIcon(zoom,'zoom');
        zoom.dataset.cropSource=refreshedImage;zoom.dataset.cropUrl=button.dataset.cropUrl;exportButton.dataset.image=refreshedImage;exportButton.dataset.fallback='0';
        if(mode==='enhance')enhancedFlag.hidden=false;else{button.dataset.mode='enhance';button.dataset.url=button.dataset.enhanceUrl}
        return{ok:true,mode};
    }catch(error){const message=error.message||(mode==='generate'?'Artwork generation failed.':'Artwork enhancement failed.');if(showAlert)alert(message);return{ok:false,message,mode}}
    finally{button.disabled=false;button.textContent=button.dataset.mode==='generate'?'Generate':'Enhance'}
}
document.querySelectorAll('.artwork-action').forEach(button=>button.addEventListener('click',()=>runArtworkAction(button)));
document.querySelectorAll('.webp-action').forEach(button=>button.addEventListener('click',async()=>{const row=button.closest('tr'),original=button.textContent;button.disabled=true;button.textContent='Converting…';try{const response=await fetch(button.dataset.url,{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':csrfToken}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'WebP conversion failed.');refreshRowArtwork(row,data.image,!row.querySelector('.enhanced-flag').hidden);refreshArtworkMetadata(row,data.bytes,data.extension);button.textContent='WebP ✓'}catch(error){alert(error.message||'WebP conversion failed.');button.textContent=original}finally{button.disabled=false}}));
document.querySelectorAll('[data-card-row]').forEach(row=>{const title=row.querySelector('.card-title-bs'),subtitle=row.querySelector('.card-subtitle-bs'),indicator=row.querySelector('.translation-status'),update=()=>{const translated=title.textContent.trim()!==''&&((row.dataset.subtitle||'').trim()===''||subtitle.textContent.trim()!=='');indicator.textContent=translated?'TRANSLATED':'NOT TRANSLATED';indicator.style.background=translated?'#14532d':'#3f3f46'};new MutationObserver(update).observe(title,{characterData:true,childList:true,subtree:true});new MutationObserver(update).observe(subtitle,{characterData:true,childList:true,subtree:true})});
(()=>{
    const rows=[...document.querySelectorAll('[data-card-row]')],selectors=rows.map(row=>row.querySelector('.card-selector')),selectAll=document.getElementById('selectVisibleCards'),count=document.getElementById('selectedCardCount'),enhance=document.getElementById('bulkEnhance'),webp=document.getElementById('bulkWebp'),translate=document.getElementById('bulkTranslate'),swap=document.getElementById('swapArtwork'),remove=document.getElementById('bulkDelete'),status=document.getElementById('bulkActionStatus');let busy=false;
    const selectedRows=()=>rows.filter(row=>row.querySelector('.card-selector').checked);
    const updateSelection=()=>{const selectedRowsNow=selectedRows(),selected=selectedRowsNow.length;count.textContent=String(selected);enhance.disabled=busy||selected===0;webp.disabled=busy||!selectedRowsNow.some(row=>row.querySelector('.webp-action'));translate.disabled=busy||selected===0;swap.disabled=busy||selected!==2;remove.disabled=busy||selected===0;selectAll.disabled=busy;selectors.forEach(selector=>{selector.disabled=busy});selectAll.checked=rows.length>0&&selected===rows.length;selectAll.indeterminate=selected>0&&selected<rows.length;if(!busy)status.textContent=selected?`${selected} card${selected===1?'':'s'} ready.`:'Select cards from this page.'};
    const setRowStatus=(row,message,type='')=>{const target=row.querySelector('.row-task-status');target.textContent=message;target.className=`row-task-status${type?' is-'+type:''}`};
    selectors.forEach(selector=>selector.addEventListener('change',updateSelection));
    selectAll.addEventListener('change',()=>{selectors.forEach(selector=>{selector.checked=selectAll.checked});updateSelection()});
    enhance.addEventListener('click',async()=>{const selected=selectedRows();if(!selected.length)return;busy=true;updateSelection();status.textContent=`Processing artwork for ${selected.length} selected card${selected.length===1?'':'s'}…`;selected.forEach(row=>setRowStatus(row,row.querySelector('.artwork-action').dataset.mode==='generate'?'Generating artwork…':'Enhancing artwork…'));const results=await Promise.all(selected.map(async row=>({row,result:await runArtworkAction(row.querySelector('.artwork-action'),{showAlert:false})})));let failed=0;results.forEach(({row,result})=>{if(result.ok)setRowStatus(row,result.mode==='generate'?'Artwork generated.':'Artwork enhanced.','success');else{failed++;setRowStatus(row,result.message,'error')}});busy=false;updateSelection();status.textContent=failed?`${results.length-failed} completed, ${failed} failed.`:`Artwork completed for ${results.length} card${results.length===1?'':'s'}.`});
    webp.addEventListener('click',async()=>{const selected=selectedRows(),eligible=selected.filter(row=>row.querySelector('.webp-action'));if(!eligible.length)return;busy=true;updateSelection();status.textContent=`Converting ${eligible.length} selected card${eligible.length===1?'':'s'} to WebP…`;eligible.forEach(row=>setRowStatus(row,'Converting to WebP…'));const results=await Promise.all(eligible.map(async row=>{try{const button=row.querySelector('.webp-action'),response=await fetch(button.dataset.url,{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':csrfToken}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'WebP conversion failed.');refreshRowArtwork(row,data.image,!row.querySelector('.enhanced-flag').hidden);refreshArtworkMetadata(row,data.bytes,data.extension);button.textContent='WebP ✓';setRowStatus(row,'Converted to WebP.','success');return true}catch(error){setRowStatus(row,error.message||'WebP conversion failed.','error');return false}}));const completed=results.filter(Boolean).length,failed=results.length-completed,skipped=selected.length-eligible.length;busy=false;updateSelection();status.textContent=`${completed} converted${failed?`, ${failed} failed`:''}${skipped?`, ${skipped} skipped`:''}.`});
    translate.addEventListener('click',async()=>{const selected=selectedRows();if(!selected.length)return;busy=true;updateSelection();status.textContent=`Translating ${selected.length} selected card${selected.length===1?'':'s'}…`;selected.forEach(row=>setRowStatus(row,'Translating to Bosnian…'));const results=await Promise.all(selected.map(async row=>{try{const response=await fetch(row.dataset.translateUrl,{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrfToken},body:JSON.stringify({title:row.dataset.title,subtitle:row.dataset.subtitle||null,save:true})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Bosnian translation failed.');row.querySelector('.card-title-bs').textContent=data.title_bs;row.querySelector('.card-subtitle-bs').textContent=data.subtitle_bs||'';setRowStatus(row,`Saved via ${data.provider}.`,'success');return true}catch(error){setRowStatus(row,error.message||'Bosnian translation failed.','error');return false}}));const completed=results.filter(Boolean).length,failed=results.length-completed;busy=false;updateSelection();status.textContent=failed?`${completed} translated, ${failed} failed.`:`Bosnian translation saved for ${completed} card${completed===1?'':'s'}.`});
    swap.addEventListener('click',async()=>{const selected=selectedRows();if(selected.length!==2)return;busy=true;updateSelection();status.textContent='Swapping artwork…';try{const response=await fetch(swapArtworkUrl,{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrfToken},body:JSON.stringify({ids:selected.map(row=>Number(row.dataset.cardId))})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Artwork could not be swapped.');data.cards.forEach(card=>{const row=rows.find(item=>Number(item.dataset.cardId)===Number(card.id));if(row&&card.image){refreshRowArtwork(row,card.image,card.artwork_enhanced);refreshArtworkMetadata(row,card.bytes,card.extension)}});status.textContent='Artwork swapped.'}catch(error){status.textContent=error.message||'Artwork could not be swapped.'}finally{busy=false;updateSelection()}});
    remove.addEventListener('click',async()=>{const selected=selectedRows();if(!selected.length||!confirm(`Delete ${selected.length} selected card${selected.length===1?'':'s'}? This cannot be undone.`))return;busy=true;updateSelection();status.textContent=`Deleting ${selected.length} card${selected.length===1?'':'s'}…`;try{const response=await fetch(bulkDeleteUrl,{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrfToken},body:JSON.stringify({ids:selected.map(row=>Number(row.dataset.cardId))})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Cards could not be deleted.');status.textContent=`Deleted ${data.deleted} card${data.deleted===1?'':'s'}.`;location.reload()}catch(error){status.textContent=error.message||'Cards could not be deleted.';busy=false;updateSelection()}});
    updateSelection();
})();
(()=>{
    const modal=document.getElementById('artworkPicker'),closeButton=document.getElementById('artworkPickerClose');let activeRow=null,activeTrigger=null,busy=false;
    function close(){if(busy)return;modal.hidden=true;document.body.classList.remove('table-cropper-open');activeTrigger?.focus();activeRow=null;activeTrigger=null}
    function open(trigger){activeTrigger=trigger;activeRow=trigger.closest('[data-card-row]');modal.hidden=false;document.body.classList.add('table-cropper-open')}
    document.addEventListener('click',event=>{const trigger=event.target.closest('[data-change-artwork]');if(!trigger)return;event.preventDefault();open(trigger)});
    closeButton.addEventListener('click',close);modal.addEventListener('click',event=>{if(event.target===modal)close()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)close()});
    modal.querySelectorAll('[data-artwork-source-card]').forEach(choice=>choice.addEventListener('click',async()=>{if(!activeRow||busy)return;busy=true;choice.disabled=true;try{const response=await fetch(activeRow.dataset.assignUrl,{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrfToken},body:JSON.stringify({source_card_id:Number(choice.dataset.artworkSourceCard)})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Artwork could not be changed.');refreshRowArtwork(activeRow,data.image,data.artwork_enhanced);refreshArtworkMetadata(activeRow,data.bytes,data.extension);const rowStatus=activeRow.querySelector('.row-task-status');rowStatus.textContent='Artwork changed.';rowStatus.className='row-task-status is-success';busy=false;choice.disabled=false;close()}catch(error){busy=false;choice.disabled=false;alert(error.message||'Artwork could not be changed.')}}));
})();
(()=>{
    const modal=document.getElementById('tableCropper'),frame=document.getElementById('tableCropFrame'),canvas=document.getElementById('tableCropCanvas'),context=canvas.getContext('2d'),zoomInput=document.getElementById('tableCropZoom'),zoomValue=document.getElementById('tableCropZoomValue'),saveButton=document.getElementById('tableCropSave');
    const image=new Image();let trigger=null,row=null,zoom=1,offsetX=0,offsetY=0,dragging=false,lastX=0,lastY=0,ready=false;
    function dimensions(){const base=Math.min(canvas.width/image.naturalWidth,canvas.height/image.naturalHeight);return{width:image.naturalWidth*base*zoom,height:image.naturalHeight*base*zoom}}
    function clampOffset(){const size=dimensions(),xLimit=Math.max(0,size.width-canvas.width)/2,yLimit=Math.max(0,size.height-canvas.height)/2;offsetX=Math.max(-xLimit,Math.min(xLimit,offsetX));offsetY=Math.max(-yLimit,Math.min(yLimit,offsetY))}
    function draw(){if(!ready)return;clampOffset();const size=dimensions();context.fillStyle='#000';context.fillRect(0,0,canvas.width,canvas.height);context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';context.drawImage(image,(canvas.width-size.width)/2+offsetX,(canvas.height-size.height)/2+offsetY,size.width,size.height)}
    function setZoom(next){const previous=zoom;zoom=Math.max(1,Math.min(3,next));if(previous>0){offsetX*=zoom/previous;offsetY*=zoom/previous}zoomInput.value=String(zoom);zoomValue.value=`${Math.round(zoom*100)}%`;draw()}
    function close(){modal.hidden=true;document.body.classList.remove('table-cropper-open');ready=false;trigger?.focus();trigger=null;row=null}
    function open(nextTrigger){trigger=nextTrigger;row=trigger.closest('tr');zoom=1;offsetX=0;offsetY=0;ready=false;zoomInput.value='1';zoomValue.value='100%';modal.hidden=false;document.body.classList.add('table-cropper-open');image.crossOrigin=new URL(trigger.dataset.cropSource,location.href).origin===location.origin?'':'anonymous';image.src=trigger.dataset.cropSource}
    image.addEventListener('load',()=>{ready=true;draw()});image.addEventListener('error',()=>{alert('The artwork could not be loaded for cropping.');close()});
    document.addEventListener('click',event=>{const cropTrigger=event.target.closest('[data-crop-artwork]');if(!cropTrigger)return;event.preventDefault();event.stopPropagation();open(cropTrigger)});
    zoomInput.addEventListener('input',()=>setZoom(Number(zoomInput.value)));frame.addEventListener('wheel',event=>{event.preventDefault();setZoom(zoom+(event.deltaY < 0 ? .08 : -.08))},{passive:false});
    canvas.addEventListener('pointerdown',event=>{if(!ready)return;dragging=true;lastX=event.clientX;lastY=event.clientY;canvas.setPointerCapture(event.pointerId);frame.classList.add('dragging')});
    canvas.addEventListener('pointermove',event=>{if(!dragging)return;const rect=canvas.getBoundingClientRect();offsetX+=(event.clientX-lastX)*(canvas.width/rect.width);offsetY+=(event.clientY-lastY)*(canvas.height/rect.height);lastX=event.clientX;lastY=event.clientY;draw()});
    const stopDrag=()=>{dragging=false;frame.classList.remove('dragging')};canvas.addEventListener('pointerup',stopDrag);canvas.addEventListener('pointercancel',stopDrag);
    document.getElementById('tableCropReset').addEventListener('click',()=>{offsetX=0;offsetY=0;setZoom(1)});document.getElementById('tableCropClose').addEventListener('click',close);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)close()});
    saveButton.addEventListener('click',async()=>{if(!ready||!trigger||!row)return;const activeTrigger=trigger,activeRow=row;saveButton.disabled=true;saveButton.textContent='Saving…';try{draw();const cropData=canvas.toDataURL('image/jpeg',.94),response=await fetch(activeTrigger.dataset.cropUrl,{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrfToken},body:JSON.stringify({crop_data:cropData})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Artwork crop could not be saved.');const refreshedImage=`${data.image}?v=${Date.now()}`,thumb=activeRow.querySelector('.thumb'),exportButton=activeRow.querySelector('.export-card'),artworkButton=activeRow.querySelector('.artwork-action');refreshArtworkMetadata(activeRow,data.bytes,data.extension,data.image);thumb.src=refreshedImage;activeTrigger.dataset.cropSource=refreshedImage;exportButton.dataset.image=refreshedImage;exportButton.dataset.fallback='0';activeRow.querySelector('.enhanced-flag').hidden=true;artworkButton.dataset.mode='enhance';artworkButton.dataset.url=artworkButton.dataset.enhanceUrl;artworkButton.textContent='Enhance';close()}catch(error){alert(error.message||'Artwork crop could not be saved.')}finally{saveButton.disabled=false;saveButton.textContent='Save crop'}});
})();
document.querySelectorAll('.inline-score').forEach(editor=>{
    const value=editor.querySelector('.inline-score__value'),input=editor.querySelector('.inline-score__input'),error=editor.querySelector('.inline-score__error'),exportButton=editor.closest('tr').querySelector('.export-card');
    let editing=false,saving=false;
    const showError=message=>{editor.classList.add('is-error');error.textContent=message;error.hidden=false};
    const clearError=()=>{editor.classList.remove('is-error');error.hidden=true;error.textContent=''};
    const begin=()=>{if(editing||saving)return;editing=true;clearError();input.value=editor.dataset.score;value.hidden=true;input.hidden=false;input.focus();input.select()};
    const finish=()=>{editing=false;input.hidden=true;value.hidden=false};
    const save=async()=>{
        if(!editing||saving)return;
        const score=input.value.trim();
        if(score===''||!Number.isFinite(Number(score))||Number(score)<0||Number(score)>100){showError('Enter a score from 0 to 100.');input.focus();return}
        saving=true;editor.classList.add('is-saving');clearError();
        try{
            const response=await fetch(editor.dataset.url,{method:'PATCH',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrfToken},body:JSON.stringify({score})});
            const data=await response.json().catch(()=>({}));
            if(!response.ok)throw new Error(data.message||data.errors?.score?.[0]||'Score could not be saved.');
            editor.dataset.score=data.formatted_score;value.textContent=data.formatted_score;if(exportButton)exportButton.dataset.score=data.formatted_score;finish();
        }catch(saveError){showError(saveError.message||'Score could not be saved.');input.focus()}
        finally{saving=false;editor.classList.remove('is-saving')}
    };
    value.addEventListener('dblclick',begin);
    value.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();begin()}});
    input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();save()}else if(event.key==='Escape'){event.preventDefault();clearError();finish();value.focus()}});
    input.addEventListener('blur',save);
});
</script>
@endpush
