<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title', 'CMS') · Misery Index</title>
<style>
:root{color-scheme:dark;--bg:#09090b;--panel:#171717;--line:#303030;--muted:#a3a3a3;--primary:#facc15}*{box-sizing:border-box}body{background:var(--bg);color:#f5f5f5;font:15px system-ui;margin:0}a{color:inherit;text-decoration:none}header{align-items:center;background:rgba(9,9,11,.95);border-bottom:1px solid #262626;display:flex;gap:28px;padding:15px max(20px,calc((100% - 1100px)/2));position:sticky;top:0;z-index:10}header strong{color:var(--primary);font-size:20px;margin-right:auto}nav{display:flex;gap:8px}nav a{border-radius:9px;color:#bbb;font-weight:700;padding:9px 12px}nav a:hover,.active{background:#262626!important;color:var(--primary)!important}main{margin:auto;max-width:1100px;padding:28px 20px 60px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:20px}.grid{display:grid;gap:16px}.stats{grid-template-columns:repeat(auto-fit,minmax(180px,1fr))}.stat b{color:var(--primary);display:block;font-size:30px}.toolbar{align-items:center;display:flex;gap:10px;justify-content:space-between;margin-bottom:18px}.btn,button{background:var(--primary);border:0;border-radius:9px;color:#111;cursor:pointer;font-weight:850;padding:11px 15px}.btn.secondary,button.secondary{background:#292929;color:#eee}.danger{background:#7f1d1d!important;color:#fff!important}input,textarea,select{background:#0f0f10;border:1px solid #404040;border-radius:9px;color:#fff;padding:11px;width:100%}label{color:#ddd;display:block;font-weight:750;margin-bottom:6px}.field{margin-bottom:16px}.form-grid{display:grid;gap:16px;grid-template-columns:1fr 1fr}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%}th,td{border-bottom:1px solid #292929;padding:12px;text-align:left;vertical-align:middle}th{color:#999;font-size:11px;letter-spacing:1px;text-transform:uppercase}.thumb{align-items:center;background:#0b0b0c;border:1px solid #333;border-radius:9px;display:flex;height:58px;justify-content:center;object-fit:contain;width:58px}.placeholder{color:var(--primary);font-size:22px}.flash{background:#14532d;border:1px solid #22c55e;border-radius:10px;margin-bottom:16px;padding:12px}.errors{background:#450a0a;border:1px solid #ef4444;border-radius:10px;margin-bottom:16px;padding:12px}.actions{align-items:center;display:flex;gap:8px}.pagination{display:flex;gap:8px;margin-top:18px}.pagination a,.pagination span{background:#222;border-radius:7px;padding:8px}.preview{background:#0b0b0c;border:1px solid #333;border-radius:14px;display:grid;min-height:260px;place-items:center;padding:18px}.preview img{height:230px;max-width:100%;object-fit:contain}.hint{color:var(--muted);font-size:12px}.badge{background:#333;border-radius:99px;color:#ddd;font-size:11px;padding:5px 8px}@media(max-width:700px){header{align-items:flex-start;flex-direction:column;gap:10px}nav{flex-wrap:wrap}.form-grid{grid-template-columns:1fr}}
.cms-pagination{align-items:center;display:flex;gap:16px;justify-content:space-between;margin-top:18px}.cms-pagination__summary{color:var(--muted);font-size:13px}.cms-pagination__pages{align-items:center;display:flex;flex-wrap:wrap;gap:6px}.cms-pagination__pages a,.cms-pagination__pages span{align-items:center;background:#222;border:1px solid #333;border-radius:7px;display:inline-flex;font-weight:700;height:38px;justify-content:center;min-width:38px;padding:0 11px}.cms-pagination__pages a:hover{border-color:var(--primary);color:var(--primary)}.cms-pagination__pages .current{background:var(--primary);border-color:var(--primary);color:#111}.cms-pagination__pages .disabled{color:#666;cursor:not-allowed}.cms-pagination__pages .ellipsis{background:transparent;border-color:transparent;min-width:auto;padding:0 3px}@media(max-width:700px){.cms-pagination{align-items:flex-start;flex-direction:column}}
.artwork-lightbox{align-items:center;background:rgba(0,0,0,.94);display:flex;inset:0;justify-content:center;padding:32px;position:fixed;z-index:2000}.artwork-lightbox[hidden]{display:none}.artwork-lightbox img{max-height:calc(100vh - 64px);max-width:calc(100vw - 64px);object-fit:contain}.artwork-lightbox__close{position:absolute;right:20px;top:20px}
</style></head><body>
<header><strong>MISERY INDEX CMS</strong><nav>
<a href="{{ route('simulator') }}">Simulator</a><a class="{{ request()->routeIs('cms.home')?'active':'' }}" href="{{ route('cms.home') }}">Home</a>
<a class="{{ request()->routeIs('cms.cards.*')?'active':'' }}" href="{{ route('cms.cards.index') }}">Cards</a>
<a class="{{ request()->routeIs('cms.generator.*')?'active':'' }}" href="{{ route('cms.generator.index') }}">Generator</a>
<a class="{{ request()->routeIs('cms.screenshots.*')?'active':'' }}" href="{{ route('cms.screenshots.index') }}">Screenshot Maker</a>
<a class="{{ request()->routeIs('cms.content.*')?'active':'' }}" href="{{ route('cms.content.index') }}">Content</a>
<a class="{{ request()->routeIs('cms.stacks.*')?'active':'' }}" href="{{ route('cms.stacks.index') }}">Stacks</a>
</nav></header><main>
@if(session('success'))<div class="flash">{{ session('success') }}</div>@endif
@if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
@yield('content')</main><div id="artworkLightbox" class="artwork-lightbox" role="dialog" aria-modal="true" aria-label="Artwork preview" hidden><button class="artwork-lightbox__close secondary" type="button">Close</button><img alt="Enlarged card artwork"></div>@stack('scripts')<script>
(()=>{const modal=document.getElementById('artworkLightbox'),image=modal.querySelector('img'),closeButton=modal.querySelector('button');let restoreFocus=null;const close=()=>{modal.hidden=true;image.removeAttribute('src');restoreFocus?.focus();restoreFocus=null};document.addEventListener('click',event=>{const trigger=event.target.closest('[data-zoom-artwork]');if(!trigger)return;event.preventDefault();event.stopPropagation();const source=trigger.dataset.zoomSource||(trigger.matches('img')?trigger.currentSrc||trigger.src:trigger.querySelector('img')?.currentSrc||trigger.querySelector('img')?.src);if(!source)return;restoreFocus=trigger;image.src=source;modal.hidden=false;closeButton.focus()});closeButton.addEventListener('click',close);modal.addEventListener('click',event=>{if(event.target===modal)close()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)close()})})();
</script></body></html>
